[정수론] 9월 3일 -ing
Altu-Bitu-7/Altu-Bitu-ChaHyeonJu pull request #4
Opened 2024-09-03 09:47 UTC by chacha091

### 인적사항
학번: 2276321
이름: 차현주
</br>

### 과제제출
기존 제출: 1735 6588
</br>

2024-09-06 10:55 UTC, kimeunsom approved these changes
구현문제 추가제출 확인했습니다 수고하셨습니다 :)

2024-09-08 05:57 UTC, avocado8 requested changes
6588(p1)
현주님 안녕하세요 :3 6588번 문제가 백준 채점 상에서 정답 처리가 되지 않고 있습니다. 정답처리되지 않는 코드로는 출석처리가 어려우므로 코멘트 참고하셔서 수정하신 뒤 리뷰어를 다시 호출해주세요😢
질문이 있으시다면 언제든 편히 불러주세요~

2024-09-08 05:57 UTC, avocado8 commented on week3/BOJ_6588.cpp
> +const int MAX = 100000;
'백만이하의 모든 짝수에 대해서' 라고 문제에서 나와 있어요! 0이 하나 빠졌네요 :3

2024-09-08 05:57 UTC, avocado8 commented on week3/BOJ_6588.cpp
> +            prime[j]==true;
p1. 여기는 왜 비교 연산자가 들어갔을까요? 할당연산자로 수정이 필요하겠네요!
그리고 현재 로직을 보면,
i가 소수가 아니라면 continue,
i가 소수라면 i의 배수들(여기선 j겠죠?)은 소수가 아니게 되므로 소수배열에서 제외해줘야 할 것 같아요.
그렇다면 prime[j] 값을 무엇으로 바꿔줘야 할까요?

2024-09-08 05:57 UTC, avocado8 commented on week3/BOJ_6588.cpp
> +void getPrime(vector<bool>& prime){
p1. 로직이 잘못되어 올바른 답이 나오지 않고 있어요! 코멘트 참고해서 수정해주세요~

2024-09-08 05:57 UTC, avocado8 commented on week3/BOJ_6588.cpp
> +            }
p1. 3부터 n/2까지 반복문으로 쭉 소수인지 아닌지 검사할 건데, 매 반복마다 소수가 아닐 경우 "Goldbach's conjecture is wrong"을 출력하도록 설정되어 있네요. 반복이 모두 끝난 뒤에 해당 문장을 처리해주면 어떨까요?

2024-09-08 11:30 UTC, chacha091 commented
@avocado8 안녕하세요 튜터님, 6588 코드 수정했습니다!

2024-09-08 11:45 UTC, avocado8 approved these changes

2024-09-08 11:47 UTC, avocado8 commented
6588번 p1리뷰 수정 확인했습니다 :-) 튜터링 초반이라 출석처리 해드렸으나 원래는 채점 결과가 정답이 뜨지 않으면 출석으로 인정되지 않으니 꼭 확인해보신 뒤 과제를 업로드해주세요! 질문은 언제나 환영입니다☺️

2024-09-08 16:07 UTC, merged

2024-09-10 01:40 UTC, ruruisryu reviewed
1735번 너무 잘 풀어주셨습니다! 코드도 너무 완벽하고 주석도 깔끔히 잘 달아주셔서 빠르게 리뷰할 수 있었어요. 수고하셨습니다!

2024-09-10 01:40 UTC, ruruisryu commented on week3/BOJ_1735.cpp
> +int getGcd(int a, int b){   //최대공약수
getGcd함수 너무 잘 구현해주셨어요!